# Generated by Django 4.0.4 on 2023-11-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usermails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254)),
                ('subject', models.CharField(default='', max_length=100)),
                ('message', models.TextField(default='', max_length=1000)),
            ],
        ),
    ]
