# Generated by Django 4.0.4 on 2023-11-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_usermails'),
    ]

    operations = [
        migrations.CreateModel(
            name='registeredevents',
            fields=[
                ('eventid', models.AutoField(primary_key=True, serialize=False)),
                ('eventname', models.CharField(default='', max_length=100)),
                ('purpose', models.TextField(default='', max_length=1000)),
                ('location', models.CharField(default='', max_length=100)),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=50)),
            ],
        ),
    ]
