# Generated by Django 4.0.4 on 2023-11-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_registeredevents_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(default='', max_length=1000)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
